ARDUINO_DIR = /usr/share/arduino #arduino directory
ARDUINO_PORT = /dev/ttyACM* #arduino port, usually something/ttyACM*, with the star depending on the amount of devices

USER_LIB_PATH = /root/sketchbook/libraries #a path to your libraries
BOARD_TAG = uno #the arduino board you are using

include /usr/share/arduino/Arduino.mk #the arduino makefile
